### ISSUE TITLE
Error with `import10xFeatureMatrix` when reading 6 files: rownames (genes) of individual RNA objects are not equivalent

### ISSUE THREAD

**Issue by raquel-bc** [GreenleafLab/ArchR#1440]
Hi!

I got the following error using 'import10xFeatureMatrix' with 6 RNA matrices, at the step of "Merging individual RNA objects":
`Error in import10xFeatureMatrix(input = c("/path/filtered_feature_bc_matrix.h5", : Error - rownames (genes) of individual RNA objects are not equivalent.`

I used ArchR_1.0.2                

The file was correctly read when I run 'import10xFeatureMatrix' alone.

Thanks!

[ArchR-addGeneExpressionMatrix-13dd2cee9bfa-Date-2022-05-21_Time-23-07-01.log](https://github.com/GreenleafLab/ArchR/files/8748569/ArchR-addGeneExpressionMatrix-13dd2cee9bfa-Date-2022-05-21_Time-23-07-01.log)

**Comment by rcorces** [comment]
Hi @raquel-bc! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
This is a sanity check imposed on your input data. The multiple H5 files that you are trying to important do not contain the same gene names. I've never encountered this from a user before but it seems like a red flag to me.

Can you describe what your input is and (if you know how) examine the H5 files to see why your genes are different across the multiple input files? If you find a compelling reason for why this might happen, I can modify the function to allow this type of input by only using the gene names that match across the multiple input files.

**Comment by dagarfield** [comment]
Oh, I think I know this one. For reasons I do not understand, the row order is different (and possibly the resulting rowData) on the SCE that come in via this import process. Here's what I did to fix the issue. It is just two samples, but you can probably generalize:

```
seRNA <- import10xFeatureMatrix(
  input = c(RNApath1,RNApath2),
  names = c("N1_2","gp120")
)
#Error in combining individual feature matrices! Returning as a list of individual feature matrices!
#So, maybe we need to add some colData and try again?
colData(seRNA[[1]])$Sample = "N1_2"
colData(seRNA[[2]])$Sample = "gp120"
#That doesn't do it...
#Looks like the order of the features may be different?
seRNA[[1]]<-seRNA[[1]][rownames(seRNA[[2]]),] #confirm with identical(rownames(seRNA[[1]]),rownames(seRNA[[2]]))
rowRanges(seRNA[[1]])<-rowRanges(seRNA[[2]])
seRNA_combined<-cbind(seRNA[[1]],seRNA[[2]])

proj <- addGeneExpressionMatrix(input = proj, seRNA = seRNA_combined)
```

**Comment by rcorces** [comment]
@dagarfield - I think that particular issue I fixed a few weeks back in `release_1.0.2` . Now, if multiple h5 files are provided, I re-order them based on genomic coordinates:
https://github.com/GreenleafLab/ArchR/blob/706b88a80570f814b01959a5d9d536adf7ac64b4/R/MultiModal.R#L43-L46
There is something funky going on in cellranger that gives inconsistent gene/transcript definition (described here - https://github.com/GreenleafLab/ArchR/issues/507#issuecomment-1063139673)

I could add a `force` parameter here to convert some of the sanity check errors to warnings. in my original thought process, h5 files with non-identical gene names was an error not a warning but it would prevent people from importing data easily.

@raquel-bc - any update on your end?

**Comment by rcorces** [comment]
closing due to inactivity.

**Comment by rcorces** [comment]
actually, nevermind. I'll leave this one open. We can make it so that mis-matched genes are just excluded.

**Comment by Achernar121** [comment]
@rcorces Hi Ryan, Thanks for your excellent single-cell analysis package. I have the same issue when using 'import10xFeatureMatrix'  with 4 multiome sample data. I am 100% sure the problem is cellranger, which gives inconsistent gene/transcript definitions. Because if I create 4 samples into 4 ArchRproject, all samples could be input RNA matrix individually. I am also testing three of my samples that could be input RNA matrix without error. There is only one sample not compatible with other samples. I would appreciate it if you could add a force parameter to convert some of the sanity check errors to warnings or tell us how to do that.  Thanks!

**Comment by rcorces** [comment]
@Achernar121 - I've made quite a few changes to `import10xFeatureMatrix()` in the `dev_geneMismatch` branch. I havent created a test dataset with gene mismatches for this so this is more or less a blind fix. If I have time, I'll create a test dataset but would be great if you could test and report back with details.

To install:
```
devtools::install_github("GreenleafLab/ArchR", ref="dev_geneMismatch", repos = BiocManager::repositories())
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)
```

**Comment by Achernar121** [comment]
> @Achernar121 - I've made quite a few changes to `import10xFeatureMatrix()` in the `dev_geneMismatch` branch. I havent created a test dataset with gene mismatches for this so this is more or less a blind fix. If I have time, I'll create a test dataset but would be great if you could test and report back with details.
> 
> To install:
> 
> ```
> devtools::install_github("GreenleafLab/ArchR", ref="dev_geneMismatch", repos = BiocManager::repositories())
> #to unload a package and reload
> detach("package:ArchR", unload=TRUE)
> library(ArchR)
> ```

Thank you so much! It works great for me. Please tell me what kinds of detail should I report; I will try my best to gather information!

**Comment by rcorces** [comment]
I was hoping to see what the console output looks like on your end. And maybe you could just spot check a few genes (preferably with names starting with letters that are later in the alphabet) by looking at UMAP embedding of the ATAC and RNA signal to make sure that there isnt some sort of shuffling that occurred when removing the genes.

For example, if the console output says that it is removing the gene "CD4" then I might worry that genes later in the alphabet (i.e. "IRF8") might get shuffled accidentally during the removal procedure.

**Comment by Achernar121** [comment]
> I was hoping to see what the console output looks like on your end. And maybe you could just spot check a few genes (preferably with names starting with letters that are later in the alphabet) by looking at UMAP embedding of the ATAC and RNA signal to make sure that there isnt some sort of shuffling that occurred when removing the genes.
> 
> For example, if the console output says that it is removing the gene "CD4" then I might worry that genes later in the alphabet (i.e. "IRF8") might get shuffled accidentally during the removal procedure.

I got error when using `addGeneExpressionMatrix( )` function
`Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqnames’ for signature ‘"SummarizedExperiment"’`

Then I run `seqnames(seRNA)`, got the same error:
`seqnames(seRNA)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqnames’ for signature ‘"SummarizedExperiment"’`

Then I tested three of my samples that could be input RNA matrix together without error before. After `import10xFeatureMatrix()`as `seRNA2`, The` seqnames(seRNA2)` have same error. Then I switch back to the public version of ArchR 1.0.2. Using `import10xFeatureMatrix()` again with three sample as `seRNA3`. This time there is no error:
```
> seqnames(seRNA3)
factor-Rle of length 36578 with 39 runs
  Lengths:       3409       2540       1892 ...          6          1          3
  Values : chr1       chr2       chr3       ... KI270728.1 KI270731.1 KI270734.1
Levels(39): chr1 chr2 chr3 chr4 ... KI270727.1 KI270728.1 KI270731.1 KI270734.1
```
It seems that the new `import10xFeatureMatrix()` function will output a defective `SummarizedExperiment` class which couldn't get `seqnames` The seqnames slot provides the chromosome name that can then be used to get the relevant pileup from bam files. Maybe the new `import10xFeatureMatrix()` function will affect packages 'GenomicRanges' ?

**Comment by rcorces** [comment]
thanks. This appears to be a separate bug introduced recently. Will report back soon.

**Comment by rcorces** [comment]
I believe that all of this has now been fixed on `dev_geneMismatch` if you could test and confirm on your end, I would appreciate it.

**Comment by fe4960** [comment]
I tried both the master and dev_geneMismatch versions, the same error in addPeak2GeneLinks with GeneExpressionMatrix persists:
"Error in (function (classes, fdef, mtable)  : 
unable to find an inherited method for function ‘seqnames’ for signature ‘"NULL".

I don't know if it is due to some genenames in my gene list/GeneExpressionMatrix are not in the gene annotation of ArchR, so ArchR cannot find the genomic locations of these genes.

devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())
devtools::install_github("GreenleafLab/ArchR", ref="dev_geneMismatch", repos = BiocManager::repositories())

> proj <- addPeak2GeneLinks(
+   ArchRProj = proj,
+   reducedDims = "LSI_Combined",
+   useMatrix = "GeneExpressionMatrix",
+   dimsToUse = 1:30,
+   scaleDims = NULL,
+   corCutOff = 0.75,
+   k = 100,
+   knnIteration = 500,
+   overlapCutoff = 0.8,
+   maxDist = 250000,
+   scaleTo = 10^4,
+   log2Norm = TRUE,
+   predictionCutoff = 0.4,
+   seed = 1,
+   threads = max(floor(getArchRThreads()/2), 1),
+   verbose = TRUE,
+   logFile = createLogFile("addPeak2GeneLinks")
+ )
ArchR logging to : ArchRLogs/ArchR-addPeak2GeneLinks-9fb26d3ada1b-Date-2022-08-24_Time-11-59-59.log
If there is an issue, please report to github with logFile!
2022-08-24 12:00:01 : Getting Available Matrices, 0.031 mins elapsed.
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
2022-08-24 12:00:10 : Filtered Low Prediction Score Cells (0 of 86926, 0), 0.017 mins elapsed.
2022-08-24 12:00:12 : Computing KNN, 0.051 mins elapsed.
2022-08-24 12:00:13 : Identifying Non-Overlapping KNN pairs, 0.058 mins elapsed.
2022-08-24 12:00:17 : Identified 498 Groupings!, 0.125 mins elapsed.
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqnames’ for signature ‘"NULL"’

**Comment by rcorces** [comment]
@fe4960 - its unclear exactly what you've done as your post lacks sufficient details. After installing the `dev_geneMismatch` branch as shown below, you will need to re-run `import10xFeatureMatrix()` and `addGeneExpressionMatrix()` prior to re-running `addPeak2GeneLinks()`

```
devtools::install_github("GreenleafLab/ArchR", ref="dev_geneMismatch", repos = BiocManager::repositories())
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)
```

**Comment by fe4960** [comment]
Previously I did not re-run import10xFeatureMatrix() and addGeneExpressionMatrix(), they did not work. This time I installed the dev_geneMismatch branch as below and re-run import10xFeatureMatrix(), addGeneExpressionMatrix(), and addPeak2GeneLinks(). They all work. Thanks so much!

devtools::install_github("GreenleafLab/ArchR", ref="dev_geneMismatch", repos = BiocManager::repositories())
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)

**Comment by rcorces** [comment]
This has been merged into `dev` and will become part of `release_1.0.3`

**Comment by abs51295** [comment]
Hey @rcorces any idea when `1.0.3` would be released?

**Comment by rcorces** [comment]
Approximately 1 month from now but I've been saying that for 2 months already. You can always work off of `dev`. Timelines are hard for me to estimate.

**Comment by sann1458** [comment]
Hi @rcorces I am still getting this error even with the dev version of ArchR-- and it seems like the dev_geneMismatch branch is no longer available. Can you help?

**Comment by rcorces** [comment]
@sann1458 - As I'm fairly confident that this has already been addressed and fixed, I can only help if you provide a reproducible example with sufficient detail.

**Comment by sann1458** [comment]
@rcorces I have 22 multiome samples which I am trying to load with import10xFeatureMatrix. If I load individually the data is intact, e.g.:

>seRNA  ###first sample
class: RangedSummarizedExperiment 
dim: 36578 11302 
metadata(0):
assays(1): counts
rownames(36578): MIR1302-2HG FAM138A ... AC007325.4 AC007325.2
rowData names(5): feature_type genome id interval name
colnames(11302): 39_ALS_10#AAACAGCCAACCTAAT-1
  39_ALS_10#AAACAGCCACTAAATC-1 ... 39_ALS_10#TTTGTTGGTTAGTACG-1
  39_ALS_10#TTTGTTGGTTGTCCAT-1
colData names(0):

> seRNA1 ### second sample
class: RangedSummarizedExperiment 
dim: 36578 12006 
metadata(0):
assays(1): counts
rownames(36578): MIR1302-2HG FAM138A ... AC007325.4 AC007325.2
rowData names(5): feature_type genome id interval name
colnames(12006): 39_ALS_15#AAACAGCCAAGCCAGA-1
  39_ALS_15#AAACAGCCAATTGACT-1 ... 39_ALS_15#TTTGTTGGTTCGCTTG-1
  39_ALS_15#TTTGTTGGTTTGACCT-1
colData names(0):

as expected the rownames are different: 

> identical (rownames(rowData(seRNA)), rownames(rowData(seRNA1)))
[1] FALSE

If i try to load these two samples together and merge it fails: 

> seRNA3 <- import10xFeatureMatrix(
+     input = paste("/labs/mpsnyder/JCK_Sai/39_ALS_multiome/",inputFiles1,sep=""),
+     names = names(inputFiles1), strictMatch = TRUE)
Importing Feature Matrix 1 of 2
Importing Feature Matrix 2 of 2
Re-ordering RNA matricies for consistency.
Merging individual RNA objects...

Merging 39_ALS_15
Error in import10xFeatureMatrix(input = paste("/labs/mpsnyder/JCK_Sai/39_ALS_multiome/",  : 
  Error - rownames (genes) of individual RNA objects are not equivalent.
  
  > sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.3.so

Random number generation:
 RNG:     L'Ecuyer-CMRG 
 Normal:  Inversion 
 Sample:  Rejection 
 
locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] SummarizedExperiment_1.28.0 Biobase_2.54.0             
 [3] Rcpp_1.0.10                 GenomicRanges_1.46.1       
 [5] GenomeInfoDb_1.30.1         data.table_1.14.6          
 [7] stringr_1.5.0               plyr_1.8.8                 
 [9] magrittr_2.0.3              gtable_0.3.1               
[11] gtools_3.9.4                gridExtra_2.3              
[13] ArchR_1.0.2                 ggplot2_3.4.0              
[15] HDF5Array_1.22.1            rhdf5_2.38.1               
[17] DelayedArray_0.20.0         IRanges_2.28.0             
[19] S4Vectors_0.36.1            MatrixGenerics_1.6.0       
[21] matrixStats_0.63.0          BiocGenerics_0.44.0        
[23] Matrix_1.5-3                ellipsis_0.3.2             

loaded via a namespace (and not attached):
 [1] bitops_1.0-7                      fs_1.6.0                         
 [3] usethis_2.1.6                     devtools_2.4.5                   
 [5] rprojroot_2.0.3                   tools_4.1.2                      
 [7] profvis_0.3.7                     utf8_1.2.3                       
 [9] R6_2.5.1                          colorspace_2.1-0                 
[11] rhdf5filters_1.6.0                urlchecker_1.0.1                 
[13] withr_2.5.0                       tidyselect_1.2.0                 
[15] prettyunits_1.1.1                 processx_3.8.0                   
[17] curl_5.0.0                        compiler_4.1.2                   
[19] cli_3.6.0                         Cairo_1.6-0                      
[21] desc_1.4.2                        rtracklayer_1.54.0               
[23] scales_1.2.1                      callr_3.7.3                      
[25] digest_0.6.31                     Rsamtools_2.10.0                 
[27] XVector_0.34.0                    pkgconfig_2.0.3                  
[29] htmltools_0.5.4                   sessioninfo_1.2.2                
[31] fastmap_1.1.0                     BSgenome_1.62.0                  
[33] htmlwidgets_1.6.1                 rlang_1.0.6                      
[35] shiny_1.7.4                       BiocIO_1.4.0                     
[37] generics_0.1.3                    BiocParallel_1.32.5              
[39] dplyr_1.1.0                       RCurl_1.98-1.10                  
[41] GenomeInfoDbData_1.2.7            munsell_0.5.0                    
[43] Rhdf5lib_1.16.0                   fansi_1.0.4                      
[45] lifecycle_1.0.3                   stringi_1.7.12                   
[47] yaml_2.3.7                        zlibbioc_1.40.0                  
[49] pkgbuild_1.4.0                    parallel_4.1.2                   
[51] promises_1.2.0.1                  crayon_1.5.2                     
[53] miniUI_0.1.1.1                    lattice_0.20-45                  
[55] Biostrings_2.62.0                 BSgenome.Hsapiens.UCSC.hg38_1.4.4
[57] ps_1.7.2                          pillar_1.8.1                     
[59] rjson_0.2.21                      codetools_0.2-19                 
[61] pkgload_1.3.2                     XML_3.99-0.13                    
[63] glue_1.6.2                        remotes_2.4.2                    
[65] BiocManager_1.30.19               vctrs_0.5.2                      
[67] httpuv_1.6.8                      purrr_1.0.1                      
[69] cachem_1.0.6                      mime_0.12                        
[71] xtable_1.8-6                      restfulr_0.0.15                  
[73] later_1.3.0                       tibble_3.1.8                     
[75] GenomicAlignments_1.30.0          memoise_2.0.1                    
>

**Comment by rcorces** [comment]
@sann1458 - sorry this isnt a reproducible example.
Try running the new multiome tutorial which contains multiple input files. I'm still working on finalizing the next update but for the time being you can see that tutorial [here](https://rcorces.github.io/ArchR_Website_Testing/bookdown/importing-data-and-setting-up-a-multiome-project.html)

**Comment by doulijun777** [comment]
Hello, Ryan,


I also encountered such problems when I try to import10xFeatureMatrix from multiple samples (where the gene order for each sample is different). 

The error message is like "Error in import10xFeatureMatrix(input = input_rna, names = names(input_rna)) : 
  Error - rownames (genes) of individual RNA objects are not equivalent.". 
So, I tried to install ArchR as you mentioned: "devtools::install_github("GreenleafLab/ArchR", ref="dev_geneMismatch", repos = BiocManager::repositories())". 

However, it is showed that:
Downloading GitHub repo GreenleafLab/ArchR@dev_geneMismatch
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/GreenleafLab/ArchR/tarball/dev_geneMismatch'

So do you have any other suggestions to deal with this problem, thank you so much.

**Comment by rcorces** [comment]
@doulijun777 - thats because these changes were merged into the `dev` branch.

**Comment by doulijun777** [comment]
Thanks for your reply. As you mentioned , I tried to download the new version using 
devtools::install_github("GreenleafLab/ArchR", ref="dev_geneMismatch", repos = BiocManager::repositories())"."

but it showd that "Downloading GitHub repo GreenleafLab/ArchR@dev_geneMismatch
Error in utils::download.file(url, path, method = method, quiet = quiet, :
cannot open URL 'https://api.github.com/repos/GreenleafLab/ArchR/tarball/dev_geneMismatch'"

It seems that it is not available. Could you help me check it? or my download command is wrong? Thank you so much.

**Comment by doulijun777** [comment]
Sorry for the misunderstanding. Actually I have installed Archr (V1.0.2), and when I tried to add RNA information for multiple samples to the archrpoject through the codes:
seRNA <- import10xFeatureMatrix(
  input = input_rna,
  names = names(input_rna),
  strictMatch = TRUE
)

It is showed that 

Importing Feature Matrix 1 of 2
Importing Feature Matrix 2 of 2
Re-ordering RNA matricies for consistency.
Merging individual RNA objects...
Merging ALS11
Error in import10xFeatureMatrix(input = input_rna, names = names(input_rna),  :
  Error - rownames (genes) of individual RNA objects are not equivalent.


 sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /usr/lib64/libblas.so.3.4.2
LAPACK: /usr/lib64/liblapack.so.3.4.2

Random number generation:
 RNG:     L'Ecuyer-CMRG
 Normal:  Inversion
 Sample:  Rejection

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
 [1] parallel  stats4    grid      stats     graphics  grDevices utils
 [8] datasets  methods   base

other attached packages:
 [1] BSgenome.Hsapiens.UCSC.hg38_1.4.4 BSgenome_1.66.2
 [3] rtracklayer_1.58.0                Biostrings_2.66.0
 [5] XVector_0.38.0                    rhdf5_2.42.0
 [7] SummarizedExperiment_1.28.0       Biobase_2.58.0
 [9] MatrixGenerics_1.10.0             Rcpp_1.0.9
[11] Matrix_1.5-3                      GenomicRanges_1.50.2
[13] GenomeInfoDb_1.34.6               IRanges_2.32.0
[15] S4Vectors_0.36.1                  BiocGenerics_0.44.0
[17] matrixStats_0.63.0                data.table_1.14.6
[19] stringr_1.5.0                     plyr_1.8.8
[21] magrittr_2.0.3                    ggplot2_3.4.0
[23] gtable_0.3.1                      gtools_3.9.4
[25] gridExtra_2.3                     ArchR_1.0.2

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.0         lattice_0.20-45          colorspace_2.0-3
 [4] vctrs_0.5.1              generics_0.1.3           yaml_2.3.6
 [7] XML_3.99-0.13            utf8_1.2.2               rlang_1.0.6
[10] pillar_1.8.1             glue_1.6.2               withr_2.5.0
[13] DBI_1.1.3                BiocParallel_1.32.5      GenomeInfoDbData_1.2.9
[16] lifecycle_1.0.3          zlibbioc_1.44.0          munsell_0.5.0
[19] restfulr_0.0.15          codetools_0.2-18         Cairo_1.6-0
[22] fansi_1.0.3              scales_1.2.1             DelayedArray_0.24.0
[25] Rsamtools_2.14.0         rjson_0.2.21             stringi_1.7.8
[28] dplyr_1.0.10             BiocIO_1.8.0             cli_3.5.0
[31] tools_4.2.2              bitops_1.0-7             rhdf5filters_1.10.0
[34] RCurl_1.98-1.9           tibble_3.1.8             crayon_1.5.2
[37] pkgconfig_2.0.3          assertthat_0.2.1         Rhdf5lib_1.20.0
[40] R6_2.5.1                 GenomicAlignments_1.34.0 compiler_4.2.2


Do you have any suggestions for this situation? Thank you so much.

**Comment by doulijun777** [comment]
I found that the I used the ref="master" (github installation) insead of "dev" to install Archr. So, it is resolved. Thank you so much.

**Comment by hira-anis** [comment]
```
> names(inputFiles_scRNA)
[1] "2367_bloodasc" "2374_bloodasc" "7041_bloodasc" "7099_bloodasc" "7121_bloodasc"
> seRNA <- import10xFeatureMatrix(
+   input = inputFiles_scRNA,
+   names = names(inputFiles)
+ )
Importing Feature Matrix 1 of 5
Importing Feature Matrix 2 of 5
Importing Feature Matrix 3 of 5
Importing Feature Matrix 4 of 5
Importing Feature Matrix 5 of 5
Re-ordering RNA matricies for consistency.
Merging individual RNA objects...

Merging 2374_bloodasc
Error in import10xFeatureMatrix(input = inputFiles_scRNA, names = names(inputFiles)) : 
  Error - rownames (genes) of individual RNA objects are not equivalent.
> seRNA
Error: object 'seRNA' not found. 
```

Hey, i am still getting this error. I did use the following as recommended earlier. 

devtools::install_github("GreenleafLab/ArchR", ref="dev_geneMismatch", repos = BiocManager::repositories())
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)

**Comment by hira-anis** [comment]
> ```
> > names(inputFiles_scRNA)
> [1] "2367_bloodasc" "2374_bloodasc" "7041_bloodasc" "7099_bloodasc" "7121_bloodasc"
> > seRNA <- import10xFeatureMatrix(
> +   input = inputFiles_scRNA,
> +   names = names(inputFiles)
> + )
> Importing Feature Matrix 1 of 5
> Importing Feature Matrix 2 of 5
> Importing Feature Matrix 3 of 5
> Importing Feature Matrix 4 of 5
> Importing Feature Matrix 5 of 5
> Re-ordering RNA matricies for consistency.
> Merging individual RNA objects...
> 
> Merging 2374_bloodasc
> Error in import10xFeatureMatrix(input = inputFiles_scRNA, names = names(inputFiles)) : 
>   Error - rownames (genes) of individual RNA objects are not equivalent.
> > seRNA
> Error: object 'seRNA' not found. 
> ```
> 
> Hey, i am still getting this error. I did use the following as recommended earlier.
> 
> devtools::install_github("GreenleafLab/ArchR", ref="dev_geneMismatch", repos = BiocManager::repositories()) #to unload a package and reload detach("package:ArchR", unload=TRUE) library(ArchR)

> devtools::install_github("GreenleafLab/ArchR", ref="dev_geneMismatch", repos = BiocManager::repositories())
Downloading GitHub repo GreenleafLab/ArchR@dev_geneMismatch
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/GreenleafLab/ArchR/tarball/dev_geneMismatch'
Getting this error

**Comment by hira-anis** [comment]
Works when using ref = "dev" instead of ref = "dev_geneMismatch"

devtools::install_github("GreenleafLab/ArchR", ref="dev", repos = BiocManager::repositories())
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)

**Comment by qdong2023** [comment]
@rcorces I still encountered the issue. After installing the ArchR from devtools::install_github("GreenleafLab/ArchR", ref="dev", repos = BiocManager::repositories()), I can successfully import the RNA h5 files and add the gene expression matrix to ArchR project using import10xFeatureMatrix() and addGeneExpressionMatrix(), respectively. However, an error showed that the gene expression matrix doesn't exist:

> projmulti <- addIterativeLSI(
+   ArchRProj = projmulti, 
+   clusterParams = list(
+     resolution = 0.2, 
+     sampleCells = 10000,
+     n.start = 10
+   ),
+   saveIterations = FALSE,
+   useMatrix = "GeneExpressionMatrix", 
+   depthCol = "Gex_nUMI",
+   varFeatures = 2000,
+   firstSelection = "variable",
+   binarize = FALSE,
+   name = "LSI_RNA"
+ )
Checking Inputs...
ArchR logging to : ArchRLogs/ArchR-addIterativeLSI-445827695a2-Date-2023-12-28_Time-17-48-51.log
If there is an issue, please report to github with logFile!
Error in h5read(x, paste0(useMatrix, "/Info/Units")) : 
  Object 'GeneExpressionMatrix/Info/Units' does not exist in this HDF5 file.

I also tried the other two versions below, however, none of them can successfully run the import10xFeatureMatrix():
devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.2", repos = BiocManager::repositories())

Would you happen to have any suggestions? Thanks!

**Comment by shamer3** [comment]
I am also having the same issues I have tried all the suggestions above with no avail:
installing from "dev", "master" and "dev_geneMismatch" (which I cannot do due to an error) none of which fix the issue:

```
Importing Feature Matrix 1 of 3
Importing Feature Matrix 2 of 3
Importing Feature Matrix 3 of 3
Re-ordering RNA matricies for consistency.
Merging individual RNA objects...

Merging BMA_2
Error in import10xFeatureMatrix(input = c("datafiles/BMA_1/raw_feature_bc_matrix.h5",  : 
  Error - rownames (genes) of individual RNA objects are not equivalent.
```
