### ISSUE TITLE
Error creating Arrowfiles with the tutorial data 

### ISSUE THREAD

**Issue by Gregjlt** [GreenleafLab/ArchR#1860]
Hi, 

I have an issue creating Arrowfiles using the function createArrowfiles.
Using the data from the tutorial or personnal fragment files leads to the same error.
Here is the code I used : 
 
```
library(ArchR)
set.seed(1)
addArchRThreads(1)
inputFiles <- getTutorialData("Hematopoiesis")
inputFiles
addArchRGenome("hg19")
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
### )
```
And here is the output : 

```
filterFrags is no longer a valid input. Please use minFrags! Setting filterFrags value to minFrags!
filterTSS is no longer a valid input. Please use minTSS! Setting filterTSS value to minTSS!
Using GeneAnnotation set by addArchRGenome(Hg19)!
Using GeneAnnotation set by addArchRGenome(Hg19)!
ArchR logging to : ArchRLogs/ArchR-createArrows-220ee775e0ab1-Date-2023-02-28_Time-16-36-22.log
If there is an issue, please report to github with logFile!
Cleaning Temporary Files
2023-02-28 16:36:22 : Batch Execution w/ safelapply!, 0 mins elapsed.
(scATAC_BMMC_R1 : 1 of 3) Determining Arrow Method to use!
2023-02-28 16:36:22 : (scATAC_BMMC_R1 : 1 of 3) Reading In Fragments from inputFiles (readMethod = tabix), 0.001 mins elapsed.
2023-02-28 16:36:22 : (scATAC_BMMC_R1 : 1 of 3) Tabix Bed To Temporary File, 0.001 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:36:39 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 8 Percent, 0.281 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:36:53 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 17 Percent, 0.522 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:37:07 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 25 Percent, 0.754 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:37:20 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 33 Percent, 0.975 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:37:34 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 42 Percent, 1.195 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:37:47 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 50 Percent, 1.422 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:37:59 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 58 Percent, 1.622 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:38:12 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 67 Percent, 1.829 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:38:24 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 75 Percent, 2.039 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:38:37 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 83 Percent, 2.249 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:38:47 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 92 Percent, 2.412 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-02-28 16:38:57 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 100 Percent, 2.579 mins elapsed.
2023-02-28 16:38:57 : (scATAC_BMMC_R1 : 1 of 3) Successful creation of Temporary File, 2.594 mins elapsed.
2023-02-28 16:38:57 : (scATAC_BMMC_R1 : 1 of 3) Creating ArrowFile From Temporary File, 2.594 mins elapsed.

************************************************************
2023-02-28 16:39:00 : ERROR Found in .tmpToArrow for (scATAC_BMMC_R1 : 1 of 3) 
LogFile = ArchRLogs/ArchR-createArrows-220ee775e0ab1-Date-2023-02-28_Time-16-36-22.log

<simpleError in h(simpleError(msg, call)): error in evaluating the argument 'i' in selecting a method for function '[': error in evaluating the argument 'x' in selecting a method for function 'which': no method found for function 'match' and signature XRawList, XRawList>

************************************************************


************************************************************
2023-02-28 16:39:00 : ERROR Found in .tmpToArrow for (scATAC_BMMC_R1 : 1 of 3) 
LogFile = ArchRLogs/ArchR-createArrows-220ee775e0ab1-Date-2023-02-28_Time-16-36-22.log

<simpleError in .logError(e, fn = ".tmpToArrow", info = prefix, errorList = errorList,     logFile = logFile): Exiting See Error Above>

************************************************************

createArrowFiles has encountered an error, checking if any ArrowFiles completed..
2023-02-28 16:39:00 : 
ArchR logging successful to : ArchRLogs/ArchR-createArrows-220ee775e0ab1-Date-2023-02-28_Time-16-36-22.log
```

Here is the logfile : 

[ArchR-createArrows-220ee775e0ab1-Date-2023-02-28_Time-16-36-22.log](https://github.com/GreenleafLab/ArchR/files/10852113/ArchR-createArrows-220ee775e0ab1-Date-2023-02-28_Time-16-36-22.log)

Thanks for the help !

**Comment by rcorces** [comment]
Hi @Gregjlt! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Should have been addressed previously on the `dev` branch.
https://github.com/GreenleafLab/ArchR/pull/1795

to install:
```R

devtools::install_github("GreenleafLab/ArchR", ref="dev", repos = BiocManager::repositories(), upgrade = "never")
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)
```

**Comment by Gregjlt** [comment]
Thanks a lot for your answer ! 
I installed ArchR from the dev branch, unloaded and reloaded it as you explained it, however, the error persists, and I can figure  out by myself what is the problem.
Here is the error : 
```
filterFrags is no longer a valid input. Please use minFrags! Setting filterFrags value to minFrags!
filterTSS is no longer a valid input. Please use minTSS! Setting filterTSS value to minTSS!
Using GeneAnnotation set by addArchRGenome(Hg19)!
Using GeneAnnotation set by addArchRGenome(Hg19)!
ArchR logging to : ArchRLogs/ArchR-createArrows-25a192cea0f03-Date-2023-03-01_Time-10-08-35.log
If there is an issue, please report to github with logFile!
Cleaning Temporary Files
subThreading Enabled since ArchRLocking is FALSE see `addArchRLocking`
2023-03-01 10:08:36 : Batch Execution w/ safelapply!, 0 mins elapsed.
(scATAC_BMMC_R1 : 1 of 3) Determining Arrow Method to use!
2023-03-01 10:08:36 : (scATAC_BMMC_R1 : 1 of 3) Reading In Fragments from inputFiles (readMethod = tabix), 0 mins elapsed.
2023-03-01 10:08:36 : (scATAC_BMMC_R1 : 1 of 3) Tabix Bed To Temporary File, 0 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:08:52 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 8 Percent, 0.28 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:09:09 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 17 Percent, 0.55 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:09:24 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 25 Percent, 0.809 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:09:39 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 33 Percent, 1.056 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:09:54 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 42 Percent, 1.3 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:10:09 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 50 Percent, 1.552 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:10:22 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 58 Percent, 1.774 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:10:36 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 67 Percent, 2.006 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:10:50 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 75 Percent, 2.241 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:11:04 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 83 Percent, 2.476 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:11:15 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 92 Percent, 2.665 mins elapsed.
Warning: one argument not used by format '%s Reading TabixFile %s Percent'2023-03-01 10:11:27 : (scATAC_BMMC_R1 : 1 of 3) Reading TabixFile 100 Percent, 2.856 mins elapsed.
2023-03-01 10:11:28 : (scATAC_BMMC_R1 : 1 of 3) Successful creation of Temporary File, 2.874 mins elapsed.
2023-03-01 10:11:28 : (scATAC_BMMC_R1 : 1 of 3) Creating ArrowFile From Temporary File, 2.874 mins elapsed.

************************************************************
2023-03-01 10:11:31 : ERROR Found in .tmpToArrow for (scATAC_BMMC_R1 : 1 of 3) 
LogFile = ArchRLogs/ArchR-createArrows-25a192cea0f03-Date-2023-03-01_Time-10-08-35.log

<simpleError in h(simpleError(msg, call)): error in evaluating the argument 'i' in selecting a method for function '[': error in evaluating the argument 'x' in selecting a method for function 'which': no method found for function 'match' and signature XRawList, XRawList>

************************************************************


************************************************************
2023-03-01 10:11:31 : ERROR Found in .tmpToArrow for (scATAC_BMMC_R1 : 1 of 3) 
LogFile = ArchRLogs/ArchR-createArrows-25a192cea0f03-Date-2023-03-01_Time-10-08-35.log

<simpleError in .logError(e, fn = ".tmpToArrow", info = prefix, errorList = errorList,     logFile = logFile): Exiting See Error Above>

************************************************************

createArrowFiles has encountered an error, checking if any ArrowFiles completed..
2023-03-01 10:11:31 : 
ArchR logging successful to : ArchRLogs/ArchR-createArrows-25a192cea0f03-Date-2023-03-01_Time-10-08-35.log
```
And here is the script I used : 

```
library(ArchR)
set.seed(1)
addArchRThreads(1)
inputFiles <- getTutorialData("Hematopoiesis")
inputFiles
addArchRGenome("hg19")
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)
```
And here is the logfile : 
[ArchR-createArrows-25a192cea0f03-Date-2023-03-01_Time-10-08-35.log](https://github.com/GreenleafLab/ArchR/files/10859098/ArchR-createArrows-25a192cea0f03-Date-2023-03-01_Time-10-08-35.log)

Thanks a lot for your help !

**Comment by rcorces** [comment]
Thanks for reporting back. I made additional changes just now on `dev`. Can you try re-installing and see if this fixes the error?
```R
devtools::install_github("GreenleafLab/ArchR", ref="dev", repos = BiocManager::repositories(), upgrade = "never")
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)
```

**Comment by rcorces** [comment]
@Gregjlt - could you let me know if this has worked?

**Comment by Gregjlt** [comment]
Hi @rcorces , thanks for your help, it now works well for me with the tutorial data and my data ! I think you can close this issue

**Comment by rcorces** [comment]
Thanks for reporting back! Much appreciated!
