### ISSUE TITLE
getMarkerFeatures error with peakmatrix

### ISSUE THREAD

**Issue by xiangrong7** [GreenleafLab/ArchR#338]
Hello 
I run getMarkerFeatures with peakmatrix,and I have got the error 
[ArchR-getMarkerFeatures-19305200573b-Date-2020-10-10_Time-09-54-02.log](https://github.com/GreenleafLab/ArchR/files/5358332/ArchR-getMarkerFeatures-19305200573b-Date-2020-10-10_Time-09-54-02.log)

```r
> markersPeaks <- getMarkerFeatures(
+  ArchRProj = projbat2,
+  useMatrix = "PeakMatrix",
+ groupBy = "Celltype",
+ bias = c("TSSEnrichment", "log10(nFrags)"),
+ testMethod = "wilcoxon"
+  )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-19305200573b-Date-2020-10-10_Time-09-54-02.log
If there is an issue, please report to github with logFile!
2020-10-10 09:54:33 : Matching Known Biases, 0.129 mins elapsed.
2020-10-10 09:54:43 : Computing Pairwise Tests (1 of 9), 0.306 mins elapsed.
2020-10-10 09:54:43 : Computing Pairwise Tests (2 of 9), 0.307 mins elapsed.
2020-10-10 09:54:43 : Computing Pairwise Tests (3 of 9), 0.307 mins elapsed.
2020-10-10 09:54:44 : Computing Pairwise Tests (4 of 9), 0.307 mins elapsed.
2020-10-10 09:54:44 : Computing Pairwise Tests (5 of 9), 0.308 mins elapsed.
2020-10-10 09:54:44 : Computing Pairwise Tests (6 of 9), 0.308 mins elapsed.
2020-10-10 09:54:44 : Computing Pairwise Tests (7 of 9), 0.309 mins elapsed.
2020-10-10 09:54:44 : Computing Pairwise Tests (8 of 9), 0.309 mins elapsed.
2020-10-10 09:54:44 : Computing Pairwise Tests (9 of 9), 0.31 mins elapsed.
Error in .safelapply(seq_along(matchObj[[1]]), function(x) { :
Error Found Iteration 1 :
        [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
        <simpleError in `rownames<-`(`*tmp*`, value = "f186255"): attempt to set 'rownames' on an object with no dimensions>
Error Found Iteration 2 :
        [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
        <simpleError in `rownames<-`(`*tmp*`, value = "f186255"): attempt to set 'rownames' on an object with no dimensions>
Error Found Iteration 3 :
        [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
        <simpleError in `rownames<-`(`*tmp*`, value = "f186255"): attempt to set 'rownames' on an object with no dimensions>
Error Found Iteration 4 :
        [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
        <simpleError in `rownames<
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  9 function calls resulted in an error
```
When  I run getMarkerFeatures with GeneScorematrix, It works well.
[ArchR-getMarkerFeatures-1930531cf941-Date-2020-10-10_Time-10-19-24.log](https://github.com/GreenleafLab/ArchR/files/5358333/ArchR-getMarkerFeatures-1930531cf941-Date-2020-10-10_Time-10-19-24.log)

```r
 markersPeaks <- getMarkerFeatures(
+   ArchRProj = projbat2,
+   useMatrix = "GeneScoreMatrix",
+ groupBy = "Celltype",
+ bias = c("TSSEnrichment", "log10(nFrags)"),
+ testMethod = "wilcoxon"
+  )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-1930531cf941-Date-2020-10-10_Time-10-19-24.log
If there is an issue, please report to github with logFile!

2020-10-10 10:19:29 : Matching Known Biases, 0.049 mins elapsed.
2020-10-10 10:21:32 : Computing Pairwise Tests (1 of 9), 2.088 mins elapsed.
2020-10-10 10:21:32 : Computing Pairwise Tests (2 of 9), 2.088 mins elapsed.
2020-10-10 10:21:32 : Computing Pairwise Tests (3 of 9), 2.089 mins elapsed.
2020-10-10 10:21:32 : Computing Pairwise Tests (4 of 9), 2.089 mins elapsed.
2020-10-10 10:21:32 : Computing Pairwise Tests (5 of 9), 2.09 mins elapsed.
2020-10-10 10:21:32 : Computing Pairwise Tests (6 of 9), 2.09 mins elapsed.
2020-10-10 10:21:32 : Computing Pairwise Tests (7 of 9), 2.091 mins elapsed.
2020-10-10 10:21:32 : Computing Pairwise Tests (8 of 9), 2.091 mins elapsed.
2020-10-10 10:21:32 : Computing Pairwise Tests (9 of 9), 2.092 mins elapsed.

###########
2020-10-10 10:23:48 : Completed Pairwise Tests, 4.356 mins elapsed.
###########
ArchR logging successful to : ArchRLogs/ArchR-getMarkerFeatures-1930531cf941-Date-2020-10-10_Time-10-19-24.log
```
Can you give me some suggestions ?

**Comment by rcorces** [comment]
can you show the output of `getAvailableMatrices()` https://www.archrproject.com/reference/getAvailableMatrices.html

and `getPeakSet()` https://www.archrproject.com/reference/getPeakSet.html

My only other idea is that other users that have used spaces in the names of their ArchR objects have had problems. It appears that your project has a ton of spaces in the names.

**Comment by xiangrong7** [comment]
OK , I run getAvailableMatrices() and getPeakSet().
```r
> getAvailableMatrices(projbat2)
[1] "GeneScoreMatrix" "PeakMatrix"      "TileMatrix"
> getPeakSet(projbat2)
GRanges object with 289072 ranges and 12 metadata columns:
                                                           seqnames
                                                              <Rle>
                   Kidney distal tubule epithelial cell_1 scafford1
                   Kidney distal tubule epithelial cell_1 scafford1
                   Kidney distal tubule epithelial cell_1 scafford1
                   Kidney distal tubule epithelial cell_1 scafford1
                   Kidney distal tubule epithelial cell_1 scafford1
                                                      ...       ...
                   Kidney distal tubule epithelial cell_1 scafford9
                   Kidney distal tubule epithelial cell_1 scafford9
                   Kidney distal tubule epithelial cell_2 scafford9
                   Kidney distal tubule epithelial cell_1 scafford9
  Kidney collecting duct epithelial cell (principal cell) scafford9
                                                                     ranges
                                                                  <IRanges>
                   Kidney distal tubule epithelial cell_1         6682-7182
                   Kidney distal tubule epithelial cell_1         7636-8136
                   Kidney distal tubule epithelial cell_1         8177-8677
                   Kidney distal tubule epithelial cell_1         8899-9399
                   Kidney distal tubule epithelial cell_1       10574-11074
                                                      ...               ...
                   Kidney distal tubule epithelial cell_1 78819824-78820324
                   Kidney distal tubule epithelial cell_1 78831231-78831731
                   Kidney distal tubule epithelial cell_2 78832750-78833250
                   Kidney distal tubule epithelial cell_1 78856541-78857041
  Kidney collecting duct epithelial cell (principal cell) 78935697-78936197
                                                          strand |     score
                                                           <Rle> | <numeric>
                   Kidney distal tubule epithelial cell_1      * |  82.37510
                   Kidney distal tubule epithelial cell_1      * |   6.95645
                   Kidney distal tubule epithelial cell_1      * |   3.00138
                   Kidney distal tubule epithelial cell_1      * |   4.87206
                   Kidney distal tubule epithelial cell_1      * |   4.87206
                                                      ...    ... .       ...
                   Kidney distal tubule epithelial cell_1      * |  28.16700
                   Kidney distal tubule epithelial cell_1      * |  35.20130
                   Kidney distal tubule epithelial cell_2      * |   2.92873
                   Kidney distal tubule epithelial cell_1      * |  11.32820
  Kidney collecting duct epithelial cell (principal cell)      * |   6.80190
                                                          replicateScoreQuantile
                                                                       <numeric>
                   Kidney distal tubule epithelial cell_1                  0.961
                   Kidney distal tubule epithelial cell_1                  0.615
                   Kidney distal tubule epithelial cell_1                  0.187
                   Kidney distal tubule epithelial cell_1                  0.458
                   Kidney distal tubule epithelial cell_1                  0.458
                                                      ...                    ...
                   Kidney distal tubule epithelial cell_1                  0.893
                   Kidney distal tubule epithelial cell_1                  0.911
                   Kidney distal tubule epithelial cell_2                  0.349
                   Kidney distal tubule epithelial cell_1                  0.759
  Kidney collecting duct epithelial cell (principal cell)                  0.674
                                                          groupScoreQuantile
                                                                   <numeric>
                   Kidney distal tubule epithelial cell_1              0.933
                   Kidney distal tubule epithelial cell_1              0.378
                   Kidney distal tubule epithelial cell_1              0.043
                   Kidney distal tubule epithelial cell_1              0.216
                   Kidney distal tubule epithelial cell_1              0.216
                                                      ...                ...
                   Kidney distal tubule epithelial cell_1              0.817
                   Kidney distal tubule epithelial cell_1              0.849
                   Kidney distal tubule epithelial cell_2              0.117
                   Kidney distal tubule epithelial cell_1              0.572
  Kidney collecting duct epithelial cell (principal cell)              0.315
                                                          Reproducibility
                                                                <numeric>
                   Kidney distal tubule epithelial cell_1               2
                   Kidney distal tubule epithelial cell_1               2
                   Kidney distal tubule epithelial cell_1               2
                   Kidney distal tubule epithelial cell_1               2
                   Kidney distal tubule epithelial cell_1               2
                                                      ...             ...
                   Kidney distal tubule epithelial cell_1               2
                   Kidney distal tubule epithelial cell_1               2
                   Kidney distal tubule epithelial cell_2               2
                   Kidney distal tubule epithelial cell_1               2
  Kidney collecting duct epithelial cell (principal cell)               2
                                                                                                                 GroupReplicate
                                                                                                                    <character>
                   Kidney distal tubule epithelial cell_1                  Kidney distal tubule epithelial cell_1._.kidney_AK32
                   Kidney distal tubule epithelial cell_1                  Kidney distal tubule epithelial cell_1._.kidney_AK32
                   Kidney distal tubule epithelial cell_1                  Kidney distal tubule epithelial cell_1._.kidney_AK32
                   Kidney distal tubule epithelial cell_1                  Kidney distal tubule epithelial cell_1._.kidney_AK32
                   Kidney distal tubule epithelial cell_1                  Kidney distal tubule epithelial cell_1._.kidney_AK32
                                                      ...                                                                   ...
                   Kidney distal tubule epithelial cell_1                  Kidney distal tubule epithelial cell_1._.kidney_AK32
                   Kidney distal tubule epithelial cell_1                  Kidney distal tubule epithelial cell_1._.kidney_AK31
                   Kidney distal tubule epithelial cell_2                  Kidney distal tubule epithelial cell_2._.kidney_AK31
                   Kidney distal tubule epithelial cell_1                  Kidney distal tubule epithelial cell_1._.kidney_AK31
  Kidney collecting duct epithelial cell (principal cell) Kidney collecting duct epithelial cell (principal cell)._.kidney_AK32
                                                          distToGeneStart
                                                                <integer>
                   Kidney distal tubule epithelial cell_1           71583
                   Kidney distal tubule epithelial cell_1           70629
                   Kidney distal tubule epithelial cell_1           70088
                   Kidney distal tubule epithelial cell_1           69366
                   Kidney distal tubule epithelial cell_1           67691
                                                      ...             ...
                   Kidney distal tubule epithelial cell_1           46027
                   Kidney distal tubule epithelial cell_1           57434
                   Kidney distal tubule epithelial cell_2           58953
                   Kidney distal tubule epithelial cell_1           82744
  Kidney collecting duct epithelial cell (principal cell)          161900
                                                           nearestGene
                                                           <character>
                   Kidney distal tubule epithelial cell_1        GORAB
                   Kidney distal tubule epithelial cell_1        GORAB
                   Kidney distal tubule epithelial cell_1        GORAB
                   Kidney distal tubule epithelial cell_1        GORAB
                   Kidney distal tubule epithelial cell_1        GORAB
                                                      ...          ...
                   Kidney distal tubule epithelial cell_1 LOC109460853
                   Kidney distal tubule epithelial cell_1 LOC109460853
                   Kidney distal tubule epithelial cell_2 LOC109460853
                   Kidney distal tubule epithelial cell_1 LOC109460853
  Kidney collecting duct epithelial cell (principal cell) LOC109460853
                                                             peakType distToTSS
                                                          <character> <integer>
                   Kidney distal tubule epithelial cell_1      Distal     71583
                   Kidney distal tubule epithelial cell_1      Distal     70629
                   Kidney distal tubule epithelial cell_1      Distal     70088
                   Kidney distal tubule epithelial cell_1      Distal     69366
                   Kidney distal tubule epithelial cell_1      Distal     67691
                                                      ...         ...       ...
                   Kidney distal tubule epithelial cell_1      Distal     46027
                   Kidney distal tubule epithelial cell_1      Distal     57434
                   Kidney distal tubule epithelial cell_2      Distal     58953
                   Kidney distal tubule epithelial cell_1      Distal     82744
  Kidney collecting duct epithelial cell (principal cell)      Distal    161900
                                                           nearestTSS        GC
                                                          <character> <numeric>
                   Kidney distal tubule epithelial cell_1       GORAB    0.4351
                   Kidney distal tubule epithelial cell_1       GORAB    0.4331
                   Kidney distal tubule epithelial cell_1       GORAB    0.4251
                   Kidney distal tubule epithelial cell_1       GORAB    0.4371
                   Kidney distal tubule epithelial cell_1       GORAB    0.4112
                                                      ...         ...       ...
                   Kidney distal tubule epithelial cell_1       SQRDL    0.3493
                   Kidney distal tubule epithelial cell_1       SQRDL    0.4391
                   Kidney distal tubule epithelial cell_2       SQRDL    0.3852
                   Kidney distal tubule epithelial cell_1       SQRDL    0.4251
  Kidney collecting duct epithelial cell (principal cell)       SQRDL    0.3114
                                                                idx
                                                          <integer>
                   Kidney distal tubule epithelial cell_1         1
                   Kidney distal tubule epithelial cell_1         2
                   Kidney distal tubule epithelial cell_1         3
                   Kidney distal tubule epithelial cell_1         4
                   Kidney distal tubule epithelial cell_1         5
                                                      ...       ...
                   Kidney distal tubule epithelial cell_1     11410
                   Kidney distal tubule epithelial cell_1     11411
                   Kidney distal tubule epithelial cell_2     11412
                   Kidney distal tubule epithelial cell_1     11413
  Kidney collecting duct epithelial cell (principal cell)     11414
  -------
  seqinfo: 67 sequences from an unspecified genome; no seqlengths
>
  Kidney collecting duct epithelial cell (principal cell) LOC109460853
                                                             peakType distToTSS
                                                          <character> <integer>
                   Kidney distal tubule epithelial cell_1      Distal     71583
                   Kidney distal tubule epithelial cell_1      Distal     70629
                   Kidney distal tubule epithelial cell_1      Distal     70088
                   Kidney distal tubule epithelial cell_1      Distal     69366
                   Kidney distal tubule epithelial cell_1      Distal     67691
                                                      ...         ...       ...
                   Kidney distal tubule epithelial cell_1      Distal     46027
                   Kidney distal tubule epithelial cell_1      Distal     57434
                   Kidney distal tubule epithelial cell_2      Distal     58953
                   Kidney distal tubule epithelial cell_1      Distal     82744
  Kidney collecting duct epithelial cell (principal cell)      Distal    161900
                                                           nearestTSS        GC
                                                          <character> <numeric>
                   Kidney distal tubule epithelial cell_1       GORAB    0.4351
                   Kidney distal tubule epithelial cell_1       GORAB    0.4331
                   Kidney distal tubule epithelial cell_1       GORAB    0.4251
                   Kidney distal tubule epithelial cell_1       GORAB    0.4371
                   Kidney distal tubule epithelial cell_1       GORAB    0.4112
                                                      ...         ...       ...
                   Kidney distal tubule epithelial cell_1       SQRDL    0.3493
                   Kidney distal tubule epithelial cell_1       SQRDL    0.4391
                   Kidney distal tubule epithelial cell_2       SQRDL    0.3852
                   Kidney distal tubule epithelial cell_1       SQRDL    0.4251
  Kidney collecting duct epithelial cell (principal cell)       SQRDL    0.3114
                                                                idx
                                                          <integer>
                   Kidney distal tubule epithelial cell_1         1
                   Kidney distal tubule epithelial cell_1         2
                   Kidney distal tubule epithelial cell_1         3
                   Kidney distal tubule epithelial cell_1         4
                   Kidney distal tubule epithelial cell_1         5
                                                      ...       ...
                   Kidney distal tubule epithelial cell_1     11410
                   Kidney distal tubule epithelial cell_1     11411
                   Kidney distal tubule epithelial cell_2     11412
                   Kidney distal tubule epithelial cell_1     11413
  Kidney collecting duct epithelial cell (principal cell)     11414
  -------
  seqinfo: 67 sequences from an unspecified genome; no seqlengths
``

**Comment by rcorces** [comment]
My advice would be to re-run your analyses and not include spaces in any names of any objects. We dont really have a way to reproduce your error. If you re-run as suggested, please let us know if that fixes the problem.

**Comment by jgranja24** [comment]
Can you retry with threads = 1? Sometime this error is from multi-threading issues with mclapply.

**Comment by xiangrong7** [comment]
> Can you retry with threads = 1? Sometime this error is from multi-threading issues with mclapply.

Sorry，I still got the same error like belown:
```r
 markersPeaks <- getMarkerFeatures(

+   ArchRProj = projbat2,
+   useMatrix = "PeakMatrix",
+   groupBy = "Celltype",
+   bias = c("TSSEnrichment", "log10(nFrags)"),
+   testMethod = "wilcoxon"
+   )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-12d45651dccc-Date-2020-10-15_Time-14-47-48.log
If there is an issue, please report to github with logFile!


2020-10-15 14:53:55 : Matching Known Biases, 0.35 mins elapsed.
2020-10-15 14:55:57 : Computing Pairwise Tests (1 of 9), 2.399 mins elapsed.
Error in `rownames<-`(`*tmp*`, value = rownames(featureDFy)) :
  attempt to set 'rownames' on an object with no dimensions
```

**Comment by jgranja24** [comment]
Can you try this with the new dev version? I belive I fixed it but it would be helpful if you could test it out!

devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

Please make sure to close your session after installation reopen and call the function using ArchR::getMarkerFeatures if loading an Rdata object

**Comment by xiangrong7** [comment]
> Can you try this with the new dev version? I belive I fixed it but it would be helpful if you could test it out!
> 
> devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
> 
> Please make sure to close your session after installation reopen and call the function using ArchR::getMarkerFeatures if loading an Rdata object

Thank you for your efforts ,I have try reintall ArchR, reopen R and  call the function using ArchR::getMarkerFeatures. I still get the same error. 
Maybe it's the same as What @rcorces  said,my project somewhere include a large space,even if I dont known. Early in the project, my custom gene annotaion(gene name )seemed to have some space, and even if I fixed it later, it might have had an impact. I will re-run my analysis as @rcorces said. If there are any results I will report.

```r
> library(ArchR)
Loading required package: ggplot2
Loading required package: SummarizedExperiment
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: ‘matrixStats’

The following objects are masked from ‘package:Biobase’:

    anyMissing, rowMedians


Attaching package: ‘DelayedArray’

The following objects are masked from ‘package:matrixStats’:

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from ‘package:base’:

    aperm, apply, rowsum

Loading required package: data.table
data.table 1.13.0 using 16 threads (see ?getDTthreads).  Latest news: r-datatable.com

Attaching package: ‘data.table’

The following object is masked from ‘package:SummarizedExperiment’:

    shift

The following object is masked from ‘package:GenomicRanges’:

    shift

The following object is masked from ‘package:IRanges’:

    shift

The following objects are masked from ‘package:S4Vectors’:

    first, second

Loading required package: Matrix

Attaching package: ‘Matrix’

The following object is masked from ‘package:S4Vectors’:

    expand

Loading required package: rhdf5
Loading required package: magrittr

                                                   / |
                                                 /    \
            .                                  /      |.
            \\\                              /        |.
              \\\                          /           `|.
                \\\                      /              |.
                  \                    /                |\
                  \\#####\           /                  ||
                ==###########>      /                   ||
                 \\##==......\    /                     ||
            ______ =       =|__ /__                     ||      \\\
        ,--' ,----`-,__ ___/'  --,-`-===================##========>
       \               '        ##_______ _____ ,--,__,=##,__   ///
        ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
        -,____,---'       \\####\\________________,--\\_##,/
           ___      .______        ______  __    __  .______
          /   \     |   _  \      /      ||  |  |  | |   _  \
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |
        /  /_\  \   |      /     |  |     |   __   | |      /
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|

ArchR : Version 1.0.0
For more information see our website : www.ArchRProject.com
If you encounter a bug please report : https://github.com/GreenleafLab/ArchR/issues
Setting default number of Parallel threads to 16.
> projbat2 <- loadArchRProject("/kidneyharmony/aftercallpeak1/")
Successfully loaded ArchRProject!

                                                   / |
                                                 /    \
            .                                  /      |.
            \\\                              /        |.
              \\\                          /           `|.
                \\\                      /              |.
                  \                    /                |\
                  \\#####\           /                  ||
                ==###########>      /                   ||
                 \\##==......\    /                     ||
            ______ =       =|__ /__                     ||      \\\
        ,--' ,----`-,__ ___/'  --,-`-===================##========>
       \               '        ##_______ _____ ,--,__,=##,__   ///
        ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
        -,____,---'       \\####\\________________,--\\_##,/
           ___      .______        ______  __    __  .______
          /   \     |   _  \      /      ||  |  |  | |   _  \
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |
        /  /_\  \   |      /     |  |     |   __   | |      /
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|

> markersPeaks <- ArchR::getMarkerFeatures(
+   ArchRProj = projbat2,
+   useMatrix = "PeakMatrix",
+   groupBy = "Celltype",
+   bias = c("TSSEnrichment", "log10(nFrags)"),
+   testMethod = "wilcoxon"
+   )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-208f4cd5d91-Date-2020-10-15_Time-16-53-58.log
If there is an issue, please report to github with logFile!

2020-10-15 16:54:13 : Matching Known Biases, 0.037 mins elapsed.
2020-10-15 16:55:18 : Computing Pairwise Tests (1 of 9), 1.127 mins elapsed.
2020-10-15 16:55:18 : Computing Pairwise Tests (2 of 9), 1.127 mins elapsed.
2020-10-15 16:55:18 : Computing Pairwise Tests (3 of 9), 1.127 mins elapsed.
2020-10-15 16:55:18 : Computing Pairwise Tests (4 of 9), 1.128 mins elapsed.
2020-10-15 16:55:18 : Computing Pairwise Tests (5 of 9), 1.128 mins elapsed.
2020-10-15 16:55:18 : Computing Pairwise Tests (6 of 9), 1.129 mins elapsed.
2020-10-15 16:55:18 : Computing Pairwise Tests (7 of 9), 1.129 mins elapsed.
2020-10-15 16:55:18 : Computing Pairwise Tests (8 of 9), 1.13 mins elapsed.
2020-10-15 16:55:18 : Computing Pairwise Tests (9 of 9), 1.13 mins elapsed.
Error in .safelapply(seq_along(matchObj[[1]]), function(x) { :
Error Found Iteration 1 :
        [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
        <simpleError in `rownames<-`(`*tmp*`, value = "f186255"): attempt to set 'rownames' on an object with no dimensions>
Error Found Iteration 2 :
        [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
        <simpleError in `rownames<-`(`*tmp*`, value = "f186255"): attempt to set 'rownames' on an object with no dimensions>
Error Found Iteration 3 :
        [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
        <simpleError in `rownames<-`(`*tmp*`, value = "f186255"): attempt to set 'rownames' on an object with no dimensions>
Error Found Iteration 4 :
        [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
        <simpleError in `rownames<
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  9 function calls resulted in an error

```

**Comment by jgranja24** [comment]
Thanks, can you attach the logfile?

**Comment by xiangrong7** [comment]
There is my logfile.
[ArchR-addPeakMatrix-3e405101007b-Date-2020-10-18_Time-14-42-29.log](https://github.com/GreenleafLab/ArchR/files/5397166/ArchR-addPeakMatrix-3e405101007b-Date-2020-10-18_Time-14-42-29.log)

My genome has 91 scafford,but only 45 scafford have Peak.There has some influence ?
```r
> df = getPeakSet(projbat)
> df@seqnames
factor-Rle of length 266110 with 45 runs
  Lengths:      53753       9112      10454 ...          3      10447
  Values :  scafford1 scafford10 scafford11 ... scafford88  scafford9
Levels(69): scafford1 scafford10 scafford11 ... scafford9 scafford90 scafford91
> levels(df@seqnames)
 [1] "scafford1"  "scafford10" "scafford11" "scafford12" "scafford13"
 [6] "scafford14" "scafford15" "scafford16" "scafford17" "scafford18"
[11] "scafford19" "scafford2"  "scafford20" "scafford21" "scafford22"
[16] "scafford23" "scafford24" "scafford25" "scafford26" "scafford27"
[21] "scafford28" "scafford29" "scafford3"  "scafford30" "scafford31"
[26] "scafford32" "scafford33" "scafford34" "scafford35" "scafford36"
[31] "scafford37" "scafford4"  "scafford40" "scafford41" "scafford49"
[36] "scafford5"  "scafford50" "scafford53" "scafford54" "scafford55"
[41] "scafford57" "scafford58" "scafford59" "scafford6"  "scafford62"
[46] "scafford64" "scafford65" "scafford67" "scafford68" "scafford69"
[51] "scafford7"  "scafford70" "scafford74" "scafford76" "scafford79"
[56] "scafford8"  "scafford80" "scafford81" "scafford82" "scafford83"
[61] "scafford84" "scafford85" "scafford86" "scafford87" "scafford88"
[66] "scafford89" "scafford9"  "scafford90" "scafford91"
> unique(df@seqnames)
 [1] scafford1  scafford10 scafford11 scafford12 scafford13 scafford14
 [7] scafford15 scafford16 scafford17 scafford18 scafford19 scafford2
[13] scafford20 scafford21 scafford22 scafford23 scafford24 scafford25
[19] scafford26 scafford27 scafford28 scafford29 scafford3  scafford31
[25] scafford33 scafford4  scafford41 scafford5  scafford53 scafford57
[31] scafford58 scafford6  scafford62 scafford67 scafford7  scafford74
[37] scafford76 scafford79 scafford8  scafford81 scafford84 scafford86
[43] scafford87 scafford88 scafford9
69 Levels: scafford1 scafford10 scafford11 scafford12 scafford13 ... scafford91

```

**Comment by jgranja24** [comment]
The logfile should be ArchR-getMarkerFeatures-....log?

Best

Jeff

**Comment by xiangrong7** [comment]
Sorry,There is getMarkerFeatures logfile.
[ArchR-getMarkerFeatures-3e40b469b81-Date-2020-10-19_Time-10-29-05.log](https://github.com/GreenleafLab/ArchR/files/5398726/ArchR-getMarkerFeatures-3e40b469b81-Date-2020-10-19_Time-10-29-05.log)

**Comment by jgranja24** [comment]
Umm it says you are still on **ArchR_0.9.5** in that file please use the release version and retry!

Thanks

Jeff

**Comment by xiangrong7** [comment]
> > Can you try this with the new dev version? I belive I fixed it but it would be helpful if you could test it out!
> > devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
> > Please make sure to close your session after installation reopen and call the function using ArchR::getMarkerFeatures if loading an Rdata object
> 
> Thank you for your efforts ,I have try reintall ArchR, reopen R and call the function using ArchR::getMarkerFeatures. I still get the same error.
> Maybe it's the same as What @rcorces said,my project somewhere include a large space,even if I dont known. Early in the project, my custom gene annotaion(gene name )seemed to have some space, and even if I fixed it later, it might have had an impact. I will re-run my analysis as @rcorces said. If there are any results I will report.
> 
> ```r
> > library(ArchR)
> Loading required package: ggplot2
> Loading required package: SummarizedExperiment
> Loading required package: GenomicRanges
> Loading required package: stats4
> Loading required package: BiocGenerics
> Loading required package: parallel
> 
> Attaching package: ‘BiocGenerics’
> 
> The following objects are masked from ‘package:parallel’:
> 
>     clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
>     clusterExport, clusterMap, parApply, parCapply, parLapply,
>     parLapplyLB, parRapply, parSapply, parSapplyLB
> 
> The following objects are masked from ‘package:stats’:
> 
>     IQR, mad, sd, var, xtabs
> 
> The following objects are masked from ‘package:base’:
> 
>     anyDuplicated, append, as.data.frame, basename, cbind, colnames,
>     dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
>     grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
>     order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
>     rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
>     union, unique, unsplit, which, which.max, which.min
> 
> Loading required package: S4Vectors
> 
> Attaching package: ‘S4Vectors’
> 
> The following object is masked from ‘package:base’:
> 
>     expand.grid
> 
> Loading required package: IRanges
> Loading required package: GenomeInfoDb
> Loading required package: Biobase
> Welcome to Bioconductor
> 
>     Vignettes contain introductory material; view with
>     'browseVignettes()'. To cite Bioconductor, see
>     'citation("Biobase")', and for packages 'citation("pkgname")'.
> 
> Loading required package: DelayedArray
> Loading required package: matrixStats
> 
> Attaching package: ‘matrixStats’
> 
> The following objects are masked from ‘package:Biobase’:
> 
>     anyMissing, rowMedians
> 
> 
> Attaching package: ‘DelayedArray’
> 
> The following objects are masked from ‘package:matrixStats’:
> 
>     colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges
> 
> The following objects are masked from ‘package:base’:
> 
>     aperm, apply, rowsum
> 
> Loading required package: data.table
> data.table 1.13.0 using 16 threads (see ?getDTthreads).  Latest news: r-datatable.com
> 
> Attaching package: ‘data.table’
> 
> The following object is masked from ‘package:SummarizedExperiment’:
> 
>     shift
> 
> The following object is masked from ‘package:GenomicRanges’:
> 
>     shift
> 
> The following object is masked from ‘package:IRanges’:
> 
>     shift
> 
> The following objects are masked from ‘package:S4Vectors’:
> 
>     first, second
> 
> Loading required package: Matrix
> 
> Attaching package: ‘Matrix’
> 
> The following object is masked from ‘package:S4Vectors’:
> 
>     expand
> 
> Loading required package: rhdf5
> Loading required package: magrittr
> 
>                                                    / |
>                                                  /    \
>             .                                  /      |.
>             \\\                              /        |.
>               \\\                          /           `|.
>                 \\\                      /              |.
>                   \                    /                |\
>                   \\#####\           /                  ||
>                 ==###########>      /                   ||
>                  \\##==......\    /                     ||
>             ______ =       =|__ /__                     ||      \\\
>         ,--' ,----`-,__ ___/'  --,-`-===================##========>
>        \               '        ##_______ _____ ,--,__,=##,__   ///
>         ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
>         -,____,---'       \\####\\________________,--\\_##,/
>            ___      .______        ______  __    __  .______
>           /   \     |   _  \      /      ||  |  |  | |   _  \
>          /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |
>         /  /_\  \   |      /     |  |     |   __   | |      /
>        /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
>       /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|
> 
> ArchR : Version 1.0.0
> For more information see our website : www.ArchRProject.com
> If you encounter a bug please report : https://github.com/GreenleafLab/ArchR/issues
> Setting default number of Parallel threads to 16.
> > projbat2 <- loadArchRProject("/kidneyharmony/aftercallpeak1/")
> Successfully loaded ArchRProject!
> 
>                                                    / |
>                                                  /    \
>             .                                  /      |.
>             \\\                              /        |.
>               \\\                          /           `|.
>                 \\\                      /              |.
>                   \                    /                |\
>                   \\#####\           /                  ||
>                 ==###########>      /                   ||
>                  \\##==......\    /                     ||
>             ______ =       =|__ /__                     ||      \\\
>         ,--' ,----`-,__ ___/'  --,-`-===================##========>
>        \               '        ##_______ _____ ,--,__,=##,__   ///
>         ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
>         -,____,---'       \\####\\________________,--\\_##,/
>            ___      .______        ______  __    __  .______
>           /   \     |   _  \      /      ||  |  |  | |   _  \
>          /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |
>         /  /_\  \   |      /     |  |     |   __   | |      /
>        /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
>       /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|
> 
> > markersPeaks <- ArchR::getMarkerFeatures(
> +   ArchRProj = projbat2,
> +   useMatrix = "PeakMatrix",
> +   groupBy = "Celltype",
> +   bias = c("TSSEnrichment", "log10(nFrags)"),
> +   testMethod = "wilcoxon"
> +   )
> ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-208f4cd5d91-Date-2020-10-15_Time-16-53-58.log
> If there is an issue, please report to github with logFile!
> 
> 2020-10-15 16:54:13 : Matching Known Biases, 0.037 mins elapsed.
> 2020-10-15 16:55:18 : Computing Pairwise Tests (1 of 9), 1.127 mins elapsed.
> 2020-10-15 16:55:18 : Computing Pairwise Tests (2 of 9), 1.127 mins elapsed.
> 2020-10-15 16:55:18 : Computing Pairwise Tests (3 of 9), 1.127 mins elapsed.
> 2020-10-15 16:55:18 : Computing Pairwise Tests (4 of 9), 1.128 mins elapsed.
> 2020-10-15 16:55:18 : Computing Pairwise Tests (5 of 9), 1.128 mins elapsed.
> 2020-10-15 16:55:18 : Computing Pairwise Tests (6 of 9), 1.129 mins elapsed.
> 2020-10-15 16:55:18 : Computing Pairwise Tests (7 of 9), 1.129 mins elapsed.
> 2020-10-15 16:55:18 : Computing Pairwise Tests (8 of 9), 1.13 mins elapsed.
> 2020-10-15 16:55:18 : Computing Pairwise Tests (9 of 9), 1.13 mins elapsed.
> Error in .safelapply(seq_along(matchObj[[1]]), function(x) { :
> Error Found Iteration 1 :
>         [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
>         <simpleError in `rownames<-`(`*tmp*`, value = "f186255"): attempt to set 'rownames' on an object with no dimensions>
> Error Found Iteration 2 :
>         [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
>         <simpleError in `rownames<-`(`*tmp*`, value = "f186255"): attempt to set 'rownames' on an object with no dimensions>
> Error Found Iteration 3 :
>         [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
>         <simpleError in `rownames<-`(`*tmp*`, value = "f186255"): attempt to set 'rownames' on an object with no dimensions>
> Error Found Iteration 4 :
>         [1] "Error in `rownames<-`(`*tmp*`, value = \"f186255\") : \n  attempt to set 'rownames' on an object with no dimensions\n"
>         <simpleError in `rownames<
> In addition: Warning message:
> In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
>   9 function calls resulted in an error
> ```

I have tried ArchR_1.0.0. Attach the logfile 👍 
[ArchR-getMarkerFeatures-208f4cd5d91-Date-2020-10-15_Time-16-53-58.log](https://github.com/GreenleafLab/ArchR/files/5398783/ArchR-getMarkerFeatures-208f4cd5d91-Date-2020-10-15_Time-16-53-58.log)

**Comment by jgranja24** [comment]
Hi @xiangrong7 thanks for being patient. Can you re install the release branch 1 more time and then retry. I added a few more logging steps so we can better diagnose whats going on!

devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

Best

Jeff

**Comment by xiangrong7** [comment]
Hi @jgranja24 , I reinstall and re-run analysis.Thanks for your help.


[ArchR-getMarkerFeatures-11365be22fb8-Date-2020-10-19_Time-21-53-06.log](https://github.com/GreenleafLab/ArchR/files/5402398/ArchR-getMarkerFeatures-11365be22fb8-Date-2020-10-19_Time-21-53-06.log)

**Comment by jgranja24** [comment]
I see the issue i think. There is 1 feature on Scaffold28 which is leading to the sparseMatrix -> vector conversion.

see

```
2020-10-19 21:56:03 : Ureteric epithelial cell_scafford28_scMaty, Class = numeric

Ureteric epithelial cell_scafford28_scMaty: length = 84
 kidney_AK31#AK31_BC4005_N01 kidney_AK32#AK32_BC03082_N01 
                           0                            0 
 kidney_AK31#AK31_BC3467_N02 kidney_AK32#AK32_BC01206_N01 
                           0                            0 
kidney_AK32#AK32_BC04246_N01 kidney_AK32#AK32_BC03476_N01 
                           0                            0 
```

vs

```

2020-10-19 21:56:02 : Ureteric epithelial cell_scafford27_scMaty, Class = dgCMatrix
Ureteric epithelial cell_scafford27_scMaty: nRows = 18, nCols = 84
Ureteric epithelial cell_scafford27_scMaty: NonZeroEntries = 14, EntryRange = [ 2 , 2 ]
5 x 5 sparse Matrix of class "dgCMatrix"
     kidney_AK31#AK31_BC4005_N01 kidney_AK32#AK32_BC03082_N01
[1,]                           .                            .
[2,]                           .                            .
[3,]                           .                            .
[4,]                           .                            .
[5,]                           .                            .
     kidney_AK31#AK31_BC3467_N02 kidney_AK32#AK32_BC01206_N01
[1,]                           .                            .
[2,]                           .                            .
[3,]                           .                            .
[4,]                           .                            .
[5,]                           .                            .
     kidney_AK32#AK32_BC04246_N01
[1,]                            .
[2,]                            .
[3,]                            .
[4,]                            .
[5,]                            .


```

Im working on a fix now.

Best

Jeff

**Comment by jgranja24** [comment]
So i am now adding this check -

```
library(Matrix)

.checkSparseMatrix <- function(x, ncol = NULL){
	isSM <- is(x, 'sparseMatrix')
	if(!isSM){
		if(is.null(ncol)){
			stop("ncol must not be NULL if x is not a matrix!")
		}
		cnames <- tryCatch({
			names(x)
		}, error = function(e){
			colnames(x)
		})
		if(length(cnames) != ncol){
			stop("cnames != ncol!")
		}
		x <- Matrix::Matrix(matrix(x, ncol = ncol), sparse=TRUE)
		colnames(x) <- cnames
	}
	x
}

m <- rsparsematrix(2, 10, 0.5)
colnames(m) <- paste0("c",1:10)

> m
2 x 10 sparse Matrix of class "dgCMatrix"
   [[ suppressing 10 column names ‘c1’, ‘c2’, ‘c3’ ... ]]                    
[1,] -2.5 -1.5 .  .    0.85 . .    .   -0.32 -0.77
[2,]  .    .   . -0.3 -0.61 . 0.13 1.9  .     1.60

v <- m[1,]
> v
   c1    c2    c3    c4    c5    c6    c7    c8    c9   c10 
-2.50 -1.50  0.00  0.00  0.85  0.00  0.00  0.00 -0.32 -0.77


> .checkSparseMatrix(v, length(v))
1 x 10 sparse Matrix of class "dgCMatrix"
   [[ suppressing 10 column names ‘c1’, ‘c2’, ‘c3’ ... ]]
                                         
[1,] -2.5 -1.5 . . 0.85 . . . -0.32 -0.77


> .checkSparseMatrix(m, ncol(m))
2 x 10 sparse Matrix of class "dgCMatrix"
   [[ suppressing 10 column names ‘c1’, ‘c2’, ‘c3’ ... ]]
                                                  
[1,] -2.5 -1.5 .  .    0.85 . .    .   -0.32 -0.77
[2,]  .    .   . -0.3 -0.61 . 0.13 1.9  .     1.60
```

**Comment by jgranja24** [comment]
Ok so the fix is now in the release version. Hopefully this works!

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`
Jeff

**Comment by badoi** [comment]
I had the same issue that was fixed w/ the newer release version.

**Comment by xiangrong7** [comment]
The error was fixed ! You are wonderful. Thank you! @jgranja24
