### ISSUE TITLE
getmarkerfeatures* error in release 1.0.0

### ISSUE THREAD

**Issue by breannesparta** [GreenleafLab/ArchR#346]
Hi, 

I've installed the most recent release of ArchR (1.0.0) in attempt to overcome a bug I was having in getmarkerfeatures (screen shot attached). Now I get an error much earlier in the pipeline, when plotting the initial UMAP of different cell clusters.

The error reads:

Error in check.length(gparname):
'gpar' element 'fontsize' must not be length 0
Calle: ggAlignPlots ... grob -> gpar -> validGP -> numnotnull -> check.length

The expectation is that a UMAP plot is produced. 

Thanks for your help!

![image](https://user-images.githubusercontent.com/72580063/96171137-5adc2100-0ed9-11eb-8c5f-554f31ce9464.png)

[ArchR-plotEmbedding-26b26f2fa21-Date-2020-10-15_Time-02-02-47.log](https://github.com/GreenleafLab/ArchR/files/5387021/ArchR-plotEmbedding-26b26f2fa21-Date-2020-10-15_Time-02-02-47.log)

**Comment by jgranja24** [comment]
Ok I am looking into it

**Comment by jgranja24** [comment]
Whats the code you tried above this? The logfile you attached shows it completed?

This isnt related to plotEmbedding
```
Error in check.length(gparname):
'gpar' element 'fontsize' must not be length 0
Calle: ggAlignPlots ... grob -> gpar -> validGP -> numnotnull -> check.length
```

**Comment by breannesparta** [comment]
My apologies, you are correct!

That is the most recent log file that is outputed. I was confused because no umap plot is produced. 

It looks like this is where my code is halted:

![image](https://user-images.githubusercontent.com/72580063/96206236-59344c80-0f1d-11eb-905a-e84e1ace7b79.png)

With the ArchR version available on bioconductor, this ran fine. In my original comment I was unclear about my original error. Before updating, I was able to get marker features and complete a basic analysis up to comparing marker features between two clusters, using peak annotations.

Thank you again for looking into this.

**Comment by jgranja24** [comment]
Im still not following where the error is. Can you please show the exact code leading to the error. Thanks.

**Comment by breannesparta** [comment]
Sure, the code is halted specifically at the getmarkerfeatures command, using the genescore matrix. 

Here is the code leading up to the error point:

memory.limit(size = 200000)

library(ArchR)
set.seed(1)
addArchRThreads(threads = 16)
addArchRGenome("hg38")

#input files, enter path
inputFiles<-("/media/timothyhamilton/data1/Tim_Hamilton/Breanne/scATAC/PCA01/fragments.tsv.gz")

ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = "PCA01",
  filterTSS = 3.5, #Dont set this too high because you can always increase later
  filterFrags = 2000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

doubScores <- addDoubletScores(
  input = ArrowFiles,
  k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
  knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search.
  LSIMethod = 1
)

proj <- ArchRProject(
  ArrowFiles = ArrowFiles, 
  outputDirectory = "PCA01_results_trial",
  copyArrows = TRUE #This is recommend so that you maintain an unaltered copy for later usage.
)

getAvailableMatrices(proj)
projPCA01_1 <- filterDoublets(proj)

p1 <- plotFragmentSizes(ArchRProj = projPCA01_1)
p1
p2 <- plotTSSEnrichment(ArchRProj = projPCA01_1)
plotPDF(p1,p2, name = "QC-Sample-FragSizes-TSSProfile.pdf", ArchRProj = projPCA01_1, addDOC = FALSE, width = 5, height = 5)

saveArchRProject(ArchRProj = projPCA01_1, outputDirectory = "PCA01_results_trial", load = FALSE)

#here, they recc tweaking n iterations, varfeatures, and resolution
projPCA01_1 <- addIterativeLSI(
  ArchRProj = projPCA01_1,
  useMatrix = "TileMatrix", 
  name = "IterativeLSI", 
  iterations = 3, 
  clusterParams = list( #See Seurat::FindClusters
    resolution = c(0.2), 
    sampleCells = 7500, 
    n.start = 10
  ), 
  varFeatures = 25000, 
  dimsToUse = 1:30
)

projPCA01_1 <- addClusters(
  input = projPCA01_1,
  reducedDims = "IterativeLSI",
  method = "Seurat",
  name = "Clusters",
  resolution = 0.8
)

table(projPCA01_1$Clusters)

projPCA01_1 <- addUMAP(
  ArchRProj = projPCA01_1, 
  reducedDims = "IterativeLSI", 
  name = "UMAP", 
  nNeighbors = 40, 
  minDist = 0.5, 
  metric = "cosine"
)

projPCA01_1 <- addTSNE(
  ArchRProj = projPCA01_1, 
  reducedDims = "IterativeLSI", 
  name = "TSNE", 
  perplexity = 20
)

p1 <- plotEmbedding(ArchRProj = projPCA01_1, colorBy = "cellColData", name = "Clusters", embedding = "UMAP")
p2 <- plotEmbedding(ArchRProj = projPCA01_1, colorBy = "cellColData", name = "Clusters", embedding = "TSNE")
ggAlignPlots(p1, p2, type = "h")
plotPDF(p1,p2, name = "Plot-UMAP-tsne-Sample-Clusters.pdf", ArchRProj = projPCA01_1, addDOC = FALSE, width = 5, height = 5)

markersGS <- getMarkerFeatures(
  ArchRProj = projPCA01_1, 
  useMatrix = "GeneScoreMatrix", 
  groupBy = "Clusters",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  testMethod = "wilcoxon"
)

**Comment by jgranja24** [comment]
Do you have the logfile for the error?

**Comment by breannesparta** [comment]
no, no log file was produced

**Comment by jgranja24** [comment]
Hi @breannesparta,

I think the bug was with plotMarkers which has been fixed in the newest release version.

To install

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`
Also getMarkerFeatures has a logfile--

```
getMarkerFeatures <- function(
  ArchRProj = NULL,
  groupBy = "Clusters",
  useGroups = NULL,
  bgdGroups = NULL,
  useMatrix = "GeneScoreMatrix",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  normBy = NULL,
  testMethod = "wilcoxon",
  maxCells = 500,
  scaleTo = 10^4,
  threads = getArchRThreads(),
  k = 100,
  bufferRatio = 0.8,
  binarize = FALSE,
  useSeqnames = NULL,
  verbose = TRUE,
  **logFile = createLogFile("getMarkerFeatures")**
  ){
```


Best

Jeff

**Comment by breannesparta** [comment]
Hi Jeff,

Thank you for the update. With this new version, I was able to run the pipeline up to where I was getting my original error! Unfortunately the original error persists. I think it is a different instance of a bug in plotMarkers (screen shot attached). 

![image](https://user-images.githubusercontent.com/72580063/96798391-ae58de00-13b5-11eb-9564-30ea57621cbc.png)

The error occurs after I call peaks using MACS and then perform a marker test to identify differential peaks between two clusters. C6 has 296 cells while C4 has 1968 cells. No log file is produced for this error.  I've attached the code up to where the error occurs.

Best,

Breanne

memory.limit(size = 200000)

library(ArchR)
set.seed(1)
addArchRThreads(threads = 16)
addArchRGenome("hg38")

#input files, enter path
inputFiles<-("/media/timothyhamilton/data1/Tim_Hamilton/Breanne/scATAC/PCA01/fragments.tsv.gz")

ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = "PCA01",
  filterTSS = 3.5, #Dont set this too high because you can always increase later
  filterFrags = 3000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

doubScores <- addDoubletScores(
  input = ArrowFiles,
  k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
  knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search.
  LSIMethod = 1
)

proj <- ArchRProject(
  ArrowFiles = ArrowFiles, 
  outputDirectory = "PCA01_results_trial",
  copyArrows = TRUE #This is recommend so that you maintain an unaltered copy for later usage.
)

getAvailableMatrices(proj)
projPCA01_1 <- filterDoublets(proj)

p1 <- plotFragmentSizes(ArchRProj = projPCA01_1)
p1
p2 <- plotTSSEnrichment(ArchRProj = projPCA01_1)
plotPDF(p1,p2, name = "QC-Sample-FragSizes-TSSProfile.pdf", ArchRProj = projPCA01_1, addDOC = FALSE, width = 5, height = 5)

saveArchRProject(ArchRProj = projPCA01_1, outputDirectory = "PCA01_results_trial", load = FALSE)

#here, they recc tweaking n iterations, varfeatures, and resolution
projPCA01_1 <- addIterativeLSI(
  ArchRProj = projPCA01_1,
  useMatrix = "TileMatrix", 
  name = "IterativeLSI", 
  iterations = 3, 
  clusterParams = list( #See Seurat::FindClusters
    resolution = c(0.2), 
    sampleCells = 7500, 
    n.start = 10
  ), 
  varFeatures = 25000, 
  dimsToUse = 1:30
)

projPCA01_1 <- addClusters(
  input = projPCA01_1,
  reducedDims = "IterativeLSI",
  method = "Seurat",
  name = "Clusters",
  resolution = 0.8
)

table(projPCA01_1$Clusters)

projPCA01_1 <- addUMAP(
  ArchRProj = projPCA01_1, 
  reducedDims = "IterativeLSI", 
  name = "UMAP", 
  nNeighbors = 40, 
  minDist = 0.5, 
  metric = "cosine"
)

projPCA01_1 <- addTSNE(
  ArchRProj = projPCA01_1, 
  reducedDims = "IterativeLSI", 
  name = "TSNE", 
  perplexity = 20
)

p1 <- plotEmbedding(ArchRProj = projPCA01_1, colorBy = "cellColData", name = "Clusters", embedding = "UMAP")
p2 <- plotEmbedding(ArchRProj = projPCA01_1, colorBy = "cellColData", name = "Clusters", embedding = "TSNE")
ggAlignPlots(p1, p2, type = "h")
plotPDF(p1,p2, name = "Plot-UMAP-tsne-Sample-Clusters.pdf", ArchRProj = projPCA01_1, addDOC = FALSE, width = 5, height = 5)

markersGS <- getMarkerFeatures(
  ArchRProj = projPCA01_1, 
  useMatrix = "GeneScoreMatrix", 
  groupBy = "Clusters",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  testMethod = "wilcoxon"
)

markerList <- getMarkers(markersGS, cutOff = "FDR <= 0.01 & Log2FC >= 1.25")
markerList$C6
save(markerList, file = "markergenes.Rda")

markerGenes  <- c(
  "PAX7", "MYF5", "MYOD1", "MYOG", "MYH3", "MYH7", "MYH8", "MYF5","MYH2" 
)

heatmapGS <- markerHeatmap(
  seMarker = markersGS, 
  cutOff = "FDR <= 0.01 & Log2FC >= 1.25", 
  labelMarkers = markerGenes,
  transpose = TRUE
)

ComplexHeatmap::draw(heatmapGS, heatmap_legend_side = "bot", annotation_legend_side = "bot")
plotPDF(heatmapGS, name = "GeneScores-Marker-Heatmap.pdf", width = 8, height = 6, ArchRProj = projPCA01_1, addDOC = FALSE)

p <- plotEmbedding(
  ArchRProj = projPCA01_1, 
  colorBy = "GeneScoreMatrix", 
  name = markerGenes, 
  embedding = "UMAP",
  quantCut = c(0.01, 0.95),
  imputeWeights = NULL
)

p2 <- lapply(p, function(x){
  x + guides(color = FALSE, fill = FALSE) + 
    theme_ArchR(baseSize = 6.5) +
    theme(plot.margin = unit(c(0, 0, 0, 0), "cm")) +
    theme(
      axis.text.x=element_blank(), 
      axis.ticks.x=element_blank(), 
      axis.text.y=element_blank(), 
      axis.ticks.y=element_blank()
    )
})
do.call(cowplot::plot_grid, c(list(ncol = 3),p2))

plotPDF(plotList = p, 
        name = "Plot-UMAP-Marker-Genes-WO-Imputation.pdf", 
        ArchRProj = projPCA01_1, 
        addDOC = FALSE, width = 5, height = 5)

projPCA01_1 <- addImputeWeights(projPCA01_1)

p <- plotEmbedding(
  ArchRProj = projPCA01_1, 
  colorBy = "GeneScoreMatrix", 
  name = markerGenes, 
  embedding = "UMAP",
  imputeWeights = getImputeWeights(projPCA01_1)
)
#Rearrange for grid plotting
p2 <- lapply(p, function(x){
  x + guides(color = FALSE, fill = FALSE) + 
    theme_ArchR(baseSize = 6.5) +
    theme(plot.margin = unit(c(0, 0, 0, 0), "cm")) +
    theme(
      axis.text.x=element_blank(), 
      axis.ticks.x=element_blank(), 
      axis.text.y=element_blank(), 
      axis.ticks.y=element_blank()
    )
})
do.call(cowplot::plot_grid, c(list(ncol = 3),p2))

plotPDF(plotList = p, 
        name = "Plot-UMAP-Marker-Genes-W-Imputation.pdf", 
        ArchRProj = projPCA01_1, 
        addDOC = FALSE, width = 5, height = 5)

p <- plotBrowserTrack(
  ArchRProj = projPCA01_1, 
  groupBy = "Clusters", 
  geneSymbol = markerGenes, 
  upstream = 50000,
  downstream = 50000
)

grid::grid.newpage()
grid::grid.draw(p$PAX7)

plotPDF(plotList = p, 
        name = "Plot-Tracks-Marker-PAX7.pdf", 
        ArchRProj = projPCA01_1, 
        addDOC = FALSE, width = 5, height = 5)

grid::grid.newpage()
grid::grid.draw(p$MYF5)

plotPDF(plotList = p, 
        name = "Plot-Tracks-Marker-MYF5.pdf", 
        ArchRProj = projPCA01_1, 
        addDOC = FALSE, width = 5, height = 5)

#get reproducible peak set 
#macs2 iterative peak calling procedure

projPCA01_1 <- addGroupCoverages(ArchRProj = projPCA01_1, groupBy = "Clusters")
pathToMacs2 <- findMacs2()
projPCA01_1 <- addReproduciblePeakSet(
  ArchRProj = projPCA01_1, 
  groupBy = "Clusters", 
  pathToMacs2 = pathToMacs2
)
getPeakSet(projPCA01_1)
saveArchRProject(ArchRProj = projPCA01_1, outputDirectory = "PCA01_results_trial", load = FALSE)

projPCA01_2 <- addPeakMatrix(projPCA01_1)
getAvailableMatrices(projPCA01_2)

markersPeaks <- getMarkerFeatures(
  ArchRProj = projPCA01_2, 
  useMatrix = "PeakMatrix", 
  groupBy = "Clusters",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  testMethod = "wilcoxon"
)

markerList <- getMarkers(markersPeaks, cutOff = "FDR <= 0.01 & Log2FC >= 1")
markerList

#save(markerList, file = "markerpeaks.Rda")

heatmapPeaks <- markerHeatmap(
  seMarker = markersPeaks, 
  cutOff = "FDR <= 0.1 & Log2FC >= 0.5",
  transpose = TRUE
)
draw(heatmapPeaks, heatmap_legend_side = "bot", annotation_legend_side = "bot")
plotPDF(heatmapPeaks, name = "Peak-Marker-Heatmap.pdf", width = 8, height = 6, ArchRProj = projPCA01_2, addDOC = FALSE)

table(projPCA01_2$Clusters)

p <- plotBrowserTrack(
  ArchRProj = projPCA01_2, 
  groupBy = "Clusters", 
  geneSymbol = c("PAX7"),
  features =  getMarkers(markersPeaks, cutOff = "FDR <= 0.1 & Log2FC >= 1", returnGR = TRUE)["C6"],
  upstream = 50000,
  downstream = 50000
)

grid::grid.newpage()
grid::grid.draw(p$PAX7)

plotPDF(p, name = "Plot-Tracks-With-Features.pdf", width = 5, height = 5, ArchRProj = projPCA01_2, addDOC = FALSE)

markerTest <- getMarkerFeatures(
  ArchRProj = projPCA01_2, 
  useMatrix = "PeakMatrix",
  groupBy = "Clusters",
  testMethod = "wilcoxon",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  useGroups = "C6",
  bgdGroups = "C4"
)
#errors here
pma <- plotMarkers(seMarker = markerTest, name = "C6", cutOff = "FDR <= 0.1 & abs(Log2FC) >= 1", plotAs = "MA")
pma
pv <- plotMarkers(seMarker = markerTest, name = "C4", cutOff = "FDR <= 0.1 & abs(Log2FC) >= 1", plotAs = "Volcano")
pv
plotPDF(pma, pv, name = "c6-vs-c4-Markers-MA-Volcano.pdf", width = 5, height = 5, ArchRProj = projPCA01_2, addDOC = FALSE)

**Comment by jgranja24** [comment]
Hi @breannesparta,

When you run getMarkerFeatures like this only "C6" is available for plotMarkers. "C4" is the background set and is not a colname in markerTest. If you wanted to do what you are looking for try this -

```
markerTest <- getMarkerFeatures(
ArchRProj = projPCA01_2,
useMatrix = "PeakMatrix",
groupBy = "Clusters",
testMethod = "wilcoxon",
bias = c("TSSEnrichment", "log10(nFrags)"),
useGroups = "C6",
bgdGroups = "C4"
)

pma <- plotMarkers(seMarker = markerTest, name = "C6", cutOff = "FDR <= 0.1 & abs(Log2FC) >= 1", plotAs = "MA")
pma
```

See the change here -

```
pv <- plotMarkers(seMarker = markerTest, name = "C6", cutOff = "FDR <= 0.1 & abs(Log2FC) >= 1", plotAs = "Volcano")
pv
```

And to plot to a pdf -
`
plotPDF(pma, pv, name = "c6-vs-c4-Markers-MA-Volcano.pdf", width = 5, height = 5, ArchRProj = projPCA01_2, addDOC = FALSE)
`

Best

Jeff

**Comment by jgranja24** [comment]
I am closing this issue as the getMarkerFeatures problem has been addressed. Also I am pretty sure that the plotMarkers error is the input error as mentioned above. Feel free to continue commenting on this thread or open a new one if you have further issues!

Best

Jeff

**Comment by brianpenghe** [comment]
> I am closing this issue as the getMarkerFeatures problem has been addressed. Also I am pretty sure that the plotMarkers error is the input error as mentioned above. Feel free to continue commenting on this thread or open a new one if you have further issues!
> 
> Best
> 
> Jeff

Hi Jeff, could you take a look at a similar issue here? https://github.com/GreenleafLab/ArchR/issues/1185
It's about getting marker peaks though.
