### ISSUE TITLE
Random seed fails when ArchRThreads > 1

### ISSUE THREAD

**Issue by xiaosuyu1997** [GreenleafLab/ArchR#756]
## Describe the bug
I ran into this bug when trying to pack up the whole project and test reproducibility. I notice that the pipeline cannot reproduce even with set.seed in code. One example is "addDoubletScores"(this function don't provide "seed" parameter for random seed setting, but random seed is set in the source code:
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/DoubletsScores.R#L279-L294
The problem may be that, as ArchR is trying to parallel the process, mclapply is used, setting random seed in the main process does not guarantee that subprocesses are also reproducible (according to this [blog)](https://www.r-bloggers.com/2018/07/%F0%9F%8C%B1-setting-a-seed-in-r-when-using-parallel-simulation/).
Code block with problem is as follows: 
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/DoubletsScores.R#L531-L549
Notice that random seed is set in the main process, but sample step happens in every subprocess. By setting "RNGkind("L'Ecuyer-CMRG")" can bypass this issue, but I fear there are side effects.
I suspect other places using ".safelapply" with randomness inside may also run into this problem.

## To Reproduce
Here is a illustrative piece of code.
```r
library(parallel)

set.seed(0)

mclapply(1:10, function(i) {
  sample(1:10, 3)
})
```
Rerun the code won't produce same outputs.

## Expected behavior
Reproducibility guaranteed by random seed.

**Many thanks.**

**Comment by jeffmgranja** [comment]
Hmmm the only fix i can think of is to add a fixed seed in safelapply. Do you think that would suffice?

**Comment by jeffmgranja** [comment]
Hmm it seems like the solution you had above makes it reproducible no?

`RNGkind("L'Ecuyer-CMRG")`


```
library(parallel)

RNGkind("L'Ecuyer-CMRG")

set.seed(0)

mclapply(1:10, function(i) {
  sample(1:10, 3)
})
```

**Comment by pangxueyu233** [comment]
HI,
I also found these problems when used `addDoubletScores`, `addClusters`, `addGeneIntegrationMatrix` and etc. all funtion based on `lapply`. It would return differnt results by different seed. 
Had this problem solved in new version pakcages?

**Comment by rcorces** [comment]
Sorry for the delay in addressing this. I'm still not certain if there are other downstream effects in using

**Comment by rcorces** [comment]
Sorry for the delay in addressing this. I'm still not certain if there are other downstream effects in using RNGkind("L'Ecuyer-CMRG").

I tested this a bit on my end and I think one fix is to call `RNGkind("L'Ecuyer-CMRG")` within `addArchRThreads()` if `threads > 1`. Ive implemented that change on a new branch `dev_randomSeed` via https://github.com/GreenleafLab/ArchR/commit/e39e2784a7adc23f8476cd01c74fc4f5d5991f9b

You can test this by installing this new branch (which branches off of `release_1.0.2`), restarting R, reloading ArchR, reseting your threads with `addArchRThreads()` and then running your code.

Could you let me know if it works?

`devtools::install_github("GreenleafLab/ArchR", ref="dev_randomSeed", repos = BiocManager::repositories())`

**Comment by pangxueyu233** [comment]
Yeah, 
I've tried the new version of `ArchR`. When I excutated the following codes in different `R terminal`, it still return different results.
~~~R
library(trqwe)
library(ArchR)
# set.seed(2021)
addArchRThreads(threads = 30) 
addArchRGenome("mm10")
library(Seurat)
library(cowplot)

All_data2 <- mcreadRDS("./All_data/Save-ArchR-Project.rds")
All_merge_new <- mcreadRDS("./scRNA/ALL_MERGE_DATA_v1.rds", mc.cores = 20)

All_data2 <- addGeneIntegrationMatrix(ArchRProj = All_data2, useMatrix = "GeneScoreMatrix",matrixName = "GeneIntegrationMatrix",
    reducedDims = "IterativeLSI",seRNA = All_merge_new,addToArrow = FALSE,groupRNA = "Cell_annotation",nameCell = "pred.Cell.our",
    nameGroup = "pred.Group.our",nameScore = "pred.Score.our",threads=30,force=TRUE,nGenes=4000)
library(cowplot)
plotEmbedding(ArchRProj = All_data2, colorBy = "cellColData", name = "pred.Group.our", embedding = "TSNE",size=1)
~~~
![image](https://user-images.githubusercontent.com/40414477/134609489-e13d8e43-0d74-4ef4-bae3-a7d623c8bbef.png)
Hence, I'm cofused which one could be used in following analysis.

**Comment by rcorces** [comment]
Sorry - my previous commit wasnt fully correct. But I think https://github.com/GreenleafLab/ArchR/commit/f6ac862f62d5fa5dea0932b000ecaeed34420e3a fixed the problem.

Can you reinstall, restart R, reload ArchR, run addArchRThreads, and try again? Make sure to set a seed as well.

`devtools::install_github("GreenleafLab/ArchR", ref="dev_randomSeed", repos = BiocManager::repositories())`

This now works for me given the below minimal reproducible example:
```
library(ArchR)
addArchRThreads(16)

set.seed(0)

safelapply2 <- function(..., threads = 1, preschedule = FALSE){
  if(threads > 1){
    o <- mclapply(..., mc.cores = threads, mc.preschedule = preschedule)
  } else{
    o <- lapply(...)
  }
  o
}

i <- function(x) {
  nums <- sample(1:10, 3)
  print(paste0("Iteration ",iterations[x]))
  nums
}
iterations <- c(1:5)
safelapply2(seq_along(iterations), i, threads = 6)
```

**Comment by rcorces** [comment]
@pangxueyu233 - If you have time to confirm that the above fix works on your end, I would be very grateful. I would like to merge this into `release_1.0.2`.

**Comment by rcorces** [comment]
Closing as I believe this is solved. I merged the changes into `release_1.0.2` via https://github.com/GreenleafLab/ArchR/pull/1348.
thanks to @xiaosuyu1997 for the original report and solution.
